WebApp/Models/Vehicle.cs
using Google.Cloud.Firestore;

namespace LicensePlateCrimeWebApp.Models
{
  [FirestoreData]
  public class Vehicle : FirestoreEntity
  {
    [FirestoreProperty]
    public string OwnerId { get; set; }

    [FirestoreProperty]
    public bool IsWanted { get; set; }

    [FirestoreProperty]
    public string Model { get; set; }

    [FirestoreProperty]
    public string LicensePlate { get; set; }

    [FirestoreProperty]
    public string ImageUrl { get; set; }

    public Vehicle(string ownerId, string model, string licensePlate, string imageUrl, bool isWanted = false)
    {
      OwnerId = ownerId;
      IsWanted = isWanted;
      Model = model;
      LicensePlate = licensePlate;
      ImageUrl = imageUrl;
    }
    public Vehicle()
    {

    }
  }
}

WebApp/Controllers/VehicleController.cs
using LicensePlateCrimeWebApp.Data;
using LicensePlateCrimeWebApp.Interfaces;
using LicensePlateCrimeWebApp.Models;
using LicensePlateCrimeWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LicensePlateCrimeWebApp.Controllers
{
  [Authorize(Roles = "User")]
  public class VehicleController : Controller
  {
    private readonly FirebaseAppProvider _firebaseAppProvider;
    private readonly IVehicleRepository _vehicleRepository;

    public VehicleController(IVehicleRepository vehicleRepository, FirebaseAppProvider firebaseAppProvider)
    {
      _vehicleRepository = vehicleRepository;
      _firebaseAppProvider = firebaseAppProvider;
    }
    // GET: Vehicles
    public async Task<ActionResult> Index()
    {
      //var vehicles = await _vehicleRepository.GetAllAsync();
      var vehicles = await _vehicleRepository.GetAllFromUserIdAsync(_firebaseAppProvider.FirebaseAuthClient.User.Uid);
      return View(vehicles);
    }

    // GET: Vehicles/Details/5
    public async Task<ActionResult> Detail(string id)
    {
      var vehicle = await _vehicleRepository.GetByIdAsync(id);
      return View(vehicle);
    }

    // GET: Vehicles/Create
    public ActionResult Create()
    {
      var currentUser = _firebaseAppProvider.FirebaseAuthClient.User;
      var currentUserId = currentUser.Uid;
      var createVehicleViewModel = new CreateVehicleViewModel
      {
        OwnerId = currentUserId
      };
      return View(createVehicleViewModel);
    }

    // POST: Vehicles/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(CreateVehicleViewModel createVehicleViewModel)
    {
      if (ModelState.IsValid)
      {
        var uploadedImgUrl = await _vehicleRepository.UploadVehicleImgAsync(createVehicleViewModel.Image);
        var vehicle = new Vehicle(createVehicleViewModel.OwnerId, createVehicleViewModel.Model, createVehicleViewModel.LicensePlate, uploadedImgUrl);
        var id = await _vehicleRepository.AddAsync(vehicle);
        vehicle.Id = id;
        return RedirectToAction("Index");
      }
      else
      {
        ModelState.AddModelError("", "Photo Upload Failed");
        return View(createVehicleViewModel);
      }
    }

    [AllowAnonymous]
    public ActionResult GetVehicleInfoFromLicensePlate(string licensePlate)
    {
      var vehicle = _vehicleRepository.GetByLicensePlateAsync(licensePlate).Result;
      // return a new json that contains vehicle.Id and vehicle.Model
      return Json(new { id = vehicle?.Id, model = vehicle?.Model });
    }

    // POST: Vehicles/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Delete(string id)
    {
      var isDeleted = await _vehicleRepository.DeleteAsync(id);
      return RedirectToAction("Index", "Vehicle");
    }
  }
}

WebApp/Controllers/ViolationController.cs
using LicensePlateCrimeWebApp.Data;
using LicensePlateCrimeWebApp.Interfaces;
using LicensePlateCrimeWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LicensePlateCrimeWebApp.Controllers
{
  [Authorize(Roles = "User")]
  public class ViolationController : Controller
  {
    private readonly IViolationRepository _violationRepository;
    private readonly IVehicleRepository _vehicleRepository;
    private readonly FirebaseAppProvider _firebaseAppProvider;

    public ViolationController(IViolationRepository violationRepository, IVehicleRepository vehicleRepository, FirebaseAppProvider firebaseAppProvider)
    {
      _violationRepository = violationRepository;
      _vehicleRepository = vehicleRepository;
      _firebaseAppProvider = firebaseAppProvider;
    }

    // GET: Violations
    public async Task<ActionResult> Index(string vehicleId)
    {
      IEnumerable<Violation> violations;
      if (!String.IsNullOrEmpty(vehicleId))
      {
        violations = await _vehicleRepository.GetAllViolationsByVehicleIdAsync(vehicleId);
      }
      else
      {
        var user = _firebaseAppProvider.FirebaseAuthClient.User;
        violations = await _violationRepository.GetAllFromUserIdAsync(user.Uid);
      }

      return View(violations);
    }

    // GET: Violations/Detail/5
    public async Task<ActionResult> Detail(string id)
    {
      var violation = await _violationRepository.GetByIdAsync(id);
      return View(violation);
    }
  }
}

WebApp/Views/Vehicle/Create.cshtml
@model LicensePlateCrimeWebApp.ViewModels.CreateVehicleViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    var title = @localizer["Araçlarım - Araç Ekle"];
    ViewData["Title"] = title;
}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>@localizer["Create Vehicle"]</h2>
        <form method="POST" asp-action="Create" enctype="multipart/form-data">
            <input type="hidden" id="OwnerId" name="OwnerId" asp-for="OwnerId" />
            <div class="form-group">
                <label>@localizer["Model"]</label>
                <input asp-for="Model" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>@localizer["License Plate"]</label>
                <input asp-for="LicensePlate" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>@localizer["Image"]</label>
                <input asp-for="Image" type="file" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">@localizer["Submit"]</button>
        </form>
    </div>
</div>

WebApp/Views/Vehicle/Detail.cshtml
@using LicensePlateCrimeWebApp.Data;
@using LicensePlateCrimeWebApp.Interfaces;
@model Vehicle;
@inject FirebaseAppProvider firebaseAppProvider;
@inject IVehicleRepository _vehicleRepository;
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<style>
    .vertical-align {
        display: flex;
        align-items: center;
    }

</style>

@{
    var title = @localizer["Araçlarım - Detaylar"];
    ViewData["Title"] = title;
    var owner = await firebaseAppProvider.FirebaseAdminAuth.GetUserAsync(Model.OwnerId);
}

<!-- single -->
<div class="single">
    <div class="container">
        <div class="col-md-4 agile_single_left">
            <div class="agileits_recent_posts">
                <h3>@localizer["Info"]</h3>
                <div class="agileits_recent_posts_grid row vertical-align">
                    <div class="agileits_recent_posts_gridl col-md-6">
                        <img src="~/images/license_plate_graphic.png" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_recent_posts_gridr col-md-6">
                        <h4>@Model.LicensePlate</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="agileits_recent_posts_grid row vertical-align">
                    <div class="agileits_recent_posts_gridl col-md-6">
                        <img src="~/images/car_model_graphic.png" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_recent_posts_gridr col-md-6">
                        <h4>@Model.Model</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="agileits_recent_posts_grid row vertical-align">
                    <div class="agileits_recent_posts_gridl col-md-6">
                        <img src="~/images/date_created_graphic.png" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_recent_posts_gridr col-md-6">
                        <h4>@Model.CreationDateLocalStr</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="agileits_recent_posts_grid row vertical-align">
                    <div class="agileits_recent_posts_gridl col-md-6">
                        <img src="~/images/date_updated_graphic.png" alt=" " class="img-responsive" />
                    </div>
                    <div class="agileits_recent_posts_gridr col-md-6">
                        <h4>@Model.LastUpdateDateLocalStr</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <div class="agileits_twitter_posts">
                <h3>@localizer["Violations"]</h3>
                <ul>
                    @{
                        var violations = await _vehicleRepository.GetAllViolationsByVehicleIdAsync(Model.Id);
                    }
                    @foreach (var violation in violations)
                    {
                        <li>
                            <a asp-controller="Violation" asp-action="Detail" asp-route-id="@violation.Id">
                                <i>@violation.CreationDateLocalStr</i><span>
                                    @violation.Description - @violation.Message
                                </span>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="col-md-8 agile_single_right">
            <div class="w3_comments">
                <ul>
                    <li><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>@Model.CreationDateLocalStr</li>
                    <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span><a >@owner.Email</a></li>
                    <li>
                        <span class="glyphicon" aria-hidden="true">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-checklist" viewBox="0 0 16 16">
                                <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                                <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z" />
                            </svg>
                        </span><a asp-controller="Violation" asp-action="Index" asp-route-vehicleId="@Model.Id">@violations.Count() @localizer["Violations"]</a>
                    </li>
                </ul>
            </div>
            <h3>
                @localizer["ARAÇ DETAYLARI"]
            </h3>

            <div class="w3_comments_bottom">
                <img src=@Model.ImageUrl alt=" " class="img-responsive" />
            </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<!-- //single -->

WebApp/Views/Vehicle/Index.cshtml
@model IEnumerable<Vehicle>
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    var title = @localizer["Araçlarım"];
    ViewData["Title"] = title;
}
<!-- special-services -->
<div class="special-services">
    <div class="container">
        <h3>@localizer["Araçlarım"]</h3>
        <p class="quia">@localizer["owned by you"]</p>
        <div class="row">
            <div class="col-md-9"></div>
            <div class="wthree_more wthree_more2 col-md-3">
                <a asp-action="Create" class="btn button--wayra button--border-thick button--text-upper button--size-s">
                    <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
                    @localizer["Create"]
                </a>
            </div>
        </div>
        

        <div class="wthree_special_services">

            @if (Model.Count() == 0)
            {
                <h1>@localizer["No vehicles found"]</h1>
            }
            else
            {
                @foreach (var vehicle in Model.OrderByDescending(v => v.CreationDate))
                {
                    <div class="col-md-4 wthree_special_service_left form-group">
                        <a asp-controller="Vehicle" asp-action="Detail" asp-route-id="@vehicle.Id">
                            <img src=@vehicle.ImageUrl alt=" " class="" />
                            <h4>@vehicle.Model (@vehicle.LicensePlate)</h4>
                        </a>

                        <div class="row">
                            <div class="wthree_more wthree_more2 col-md-6">
                                <a asp-controller="Vehicle" id="vehicle-view-button" asp-action="Detail" asp-route-id="@vehicle.Id" class="button--wayra button--border-thick button--text-upper button--size-s">
                                    <i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i>
                                    @localizer["Details"]
                                </a>
                            </div>
                            <div class="wthree_more wthree_more2 col-md-6">
                                <form method="post" asp-controller="Vehicle" asp-action="Delete">
                                    @Html.AntiForgeryToken()
                                    <input type="hidden" name="id" value="@vehicle.Id" />
                                    <a id="vehicle-delete-button" href="javascript:void(0);" onclick="this.parentElement.submit();" class="button--wayra button--border-thick button--text-upper button--size-s">
                                        <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                        @localizer["Delete"]
                                    </a>
                                </form>
                            </div>
                        </div>

                    </div>
                }
            }

            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //special-services -->


<style>
    img {
        height: 300px;
        object-fit: cover;
        width: 100%;
    }

</style>