WebApp/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace LicensePlateCrimeWebApp.Controllers
{
  public class AboutController : Controller
  {
    public IActionResult Index()
    {
      return View();
    }
  }
}

WebApp/Controllers/ContactController.cs
using LicensePlateCrimeWebApp.Interfaces;
using LicensePlateCrimeWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace LicensePlateCrimeWebApp.Controllers
{
  public class ContactController : Controller
  {
    private readonly IContactRepository _contactRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public ContactController(IContactRepository contactRepository, IHttpContextAccessor httpContextAccessor)
    {
      _contactRepository = contactRepository;
      _httpContextAccessor = httpContextAccessor;
    }
    // GET: Contact
    public ActionResult Index()
    {
      return View();
    }

    // POST: Contact/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(Contact createcontactModel)
    {
      if (ModelState.IsValid)
      {

        var contact = new Contact(createcontactModel.Name, createcontactModel.Email, createcontactModel.Telephone, createcontactModel.Subject, createcontactModel.Message);
        var id = await _contactRepository.AddAsync(contact);
        contact.Id = id;
        return RedirectToAction("Index");
      }
      else
      {
        ModelState.AddModelError("", "Mesaj gönderme sırasında hata!!! Tekrar deneyiniz.");
        return View("Index", createcontactModel);
      }
    }
  }
}

WebApp/Controllers/HomeController.cs
using LicensePlateCrimeWebApp.Models;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using System.Diagnostics;

namespace LicensePlateCrimeWebApp.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;
    private readonly IHtmlLocalizer<HomeController> _localizer;
    public HomeController(ILogger<HomeController> logger, IHtmlLocalizer<HomeController> localizer)
    {
      _logger = logger;
      _localizer = localizer;
    }

    public IActionResult Index()
    {
      ViewBag.Message = TempData["accessDeniedMsg"]?.ToString();
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    #region Localization
    public IActionResult ChangeLanguage(string culture)
    {
      Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)), new CookieOptions()
      {
        Expires = DateTimeOffset.UtcNow.AddYears(1)
      });
      return Redirect(Request.Headers["Referer"].ToString());
    }
    #endregion

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

WebApp/Controllers/LoginController.cs
using FirebaseAdmin.Auth;
using LicensePlateCrimeWebApp.Data;
using LicensePlateCrimeWebApp.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using static LicensePlateCrimeWebApp.Helpers.GlobalHelpers;

namespace LicensePlateCrimeWebApp.Controllers
{
  public class LoginController : Controller
  {
    private readonly FirebaseAppProvider _firebaseAppProvider;
    private const string LOGIN_ERROR = "E-Posta veya Parola hatalı. Tekrar deneyiniz!";
    public LoginController(FirebaseAppProvider firebaseAppProvider)
    {
      _firebaseAppProvider = firebaseAppProvider;
    }

    // GET: LoginController
    public ActionResult Index(string? returnUrl)
    {
      ViewData["ReturnUrl"] = returnUrl;
      if (User.Identity != null && User.Identity.IsAuthenticated)
      {
        return RedirectToAction("Index", "Home");
      }
      return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginModel loginModel, string? returnUrl)
    {
      try
      {
        //log in the user
        var userCredential = await _firebaseAppProvider.FirebaseAuthClient
                        .SignInWithEmailAndPasswordAsync(loginModel.Email, loginModel.Password);
        var user = userCredential.User;
        string token = await user.GetIdTokenAsync();
        //saving the token in a session variable
        //if the login is successful
        if (token != null)
        {
          var isAdmin = await GetAdminStatusAsync(user.Uid);
          // Set session expiration to 5 days.
          var options = new SessionCookieOptions()
          {
            ExpiresIn = TimeSpan.FromDays(5),
          };

          // Create the session cookie. This will also verify the ID token in the process.
          // The session cookie will have the same claims as the ID token.
          var sessionCookie = await _firebaseAppProvider.FirebaseAdminAuth
              .CreateSessionCookieAsync(token, options);

          // Set cookie policy parameters as required.
          var cookieOptions = new CookieOptions()
          {
            Expires = DateTimeOffset.UtcNow.Add(options.ExpiresIn),
            HttpOnly = true,
            Secure = true,
          };
          this.Response.Cookies.Append("session", sessionCookie, cookieOptions);

          // convert user to json string
          var userInfoJson = JsonConvert.SerializeObject(user.Info);

          var claims = new List<Claim>
          {
            new Claim("Id", user.Info.Uid),
            new Claim(ClaimTypes.Email, user.Info.Email),
            new Claim("UserInfoJson", userInfoJson)
          };
          if (isAdmin)
          {
            claims.Add(new Claim(ClaimTypes.Role, "Administrator"));
          }
          else
          {
            claims.Add(new Claim(ClaimTypes.Role, "User"));
          }
          var claimsIdentity = new ClaimsIdentity(
              claims, CookieAuthenticationDefaults.AuthenticationScheme);

          var authProperties = new AuthenticationProperties { };

          await HttpContext.SignInAsync(
              CookieAuthenticationDefaults.AuthenticationScheme,
              new ClaimsPrincipal(claimsIdentity),
              authProperties);

          ViewData["ReturnUrl"] = returnUrl;

          if (isAdmin)
            return RedirectToAction("Index", "Admin");

          if (!String.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
            return LocalRedirect(returnUrl);
          else
            return RedirectToAction("Index", "Home");
        }
        //login failed
        else
        {
          ModelState.AddModelError(String.Empty, LOGIN_ERROR);
          return View("Index", loginModel);
        }
      }
      //login failed?
      catch (Firebase.Auth.FirebaseAuthException e)
      {
        if (e.Reason == Firebase.Auth.AuthErrorReason.WrongPassword)
        {
          ModelState.AddModelError(String.Empty, LOGIN_ERROR);
        }
        return View("Index", loginModel);
      }
    }

    public async Task<IActionResult> Logout()
    {
      if (_firebaseAppProvider.FirebaseAuthClient.User != null)
        _firebaseAppProvider.FirebaseAuthClient.SignOut();
      this.Response.Cookies.Delete("session");
      // Clear the existing external cookie
      await HttpContext.SignOutAsync(
          CookieAuthenticationDefaults.AuthenticationScheme);

      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AccessDenied()
    {
      TempData["accessDeniedMsg"] = "Bu sayfaya sadece erişim yetkisi uygun olan kullanıcılar erişebilir!";
      var isAdmin = await GetAdminStatusAsync(_firebaseAppProvider.FirebaseAuthClient.User.Uid);

      if (isAdmin)
        return RedirectToAction("Index", "Admin");
      else
        return RedirectToAction("Index", "Home");
    }
  }
}

WebApp/Controllers/SignupController.cs
using Firebase.Auth;
using LicensePlateCrimeWebApp.Data;
using LicensePlateCrimeWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace LicensePlateCrimeWebApp.Controllers
{
	public class SignupController : Controller
	{
		private readonly FirebaseAppProvider _firebaseAppProvider;
		private const string EMAIL_EXISTS_ERROR = "Bu e-posta adresi zaten kullanılıyor. Lütfen başka bir e-posta adresi deneyiniz.";
		public SignupController(FirebaseAppProvider firebaseAppProvider)
		{
			_firebaseAppProvider = firebaseAppProvider;
		}

		public IActionResult Index()
		{
			if (User.Identity != null && User.Identity.IsAuthenticated)
			{
				return RedirectToAction("Index", "Home");
			}
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Registration(LoginModel loginModel)
		{
			try
			{
				//create the user
				var userCredential = await _firebaseAppProvider.FirebaseAuthClient.CreateUserWithEmailAndPasswordAsync(loginModel.Email, loginModel.Password);
				var user = userCredential.User;
				var token = await user.GetIdTokenAsync();
				//log in the new user
				if (token != null)
					return RedirectToActionPreserveMethod("Login", "Login", loginModel);
			}
			catch (FirebaseAuthException e)
			{
				if (e.Reason == AuthErrorReason.EmailExists || e.Reason == AuthErrorReason.UnknownEmailAddress)
					ModelState.AddModelError(String.Empty, EMAIL_EXISTS_ERROR);
			}
			return View("Index", loginModel);
		}
	}
}

WebApp/Views/Home/Index.cshtml
@using static LicensePlateCrimeWebApp.Helpers.GlobalHelpers;
@using LicensePlateCrimeWebApp.Data;
@using Newtonsoft.Json;
@using LicensePlateCrimeWebApp.Interfaces;
@inject IVehicleRepository _vehicleRepository;
@inject IViolationRepository _violationRepository;
@inject IContactRepository _contactRepository;
@inject FirebaseAppProvider firebaseAppProvider;
@using Microsoft.AspNetCore.Mvc.Localization
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    var title = @localizer["Ana Sayfa"];
    ViewData["Title"] = title;
}

@{
    var vehicles = await _vehicleRepository.GetAllAsync();
    var violations = await _violationRepository.GetAllAsync();
    var contacts = await _contactRepository.GetAllAsync();
    // Iterate through all users. This will still retrieve users in batches,
    // buffering no more than 1000 users in memory at a time.
    var enumerator = firebaseAppProvider.FirebaseAdminAuth.ListUsersAsync(null).GetAsyncEnumerator();
    var userCount = 0;
    while (await enumerator.MoveNextAsync())
    {
        userCount++;
    }
}

@if (!String.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert alert-danger" role="alert">
        <strong>@localizer["Hata"]</strong> @ViewBag.Message
    </div>
}


<!-- banner -->
<div class="banner">
    <div class="container">
        <div class="w3ls_banner_info">
            <h2 style="color:white;">@localizer["PLAKA CEZA SİSTEMİ"]</h2><br />
        </div>
    </div>
</div>
<!-- //banner -->
<!-- banner-bottom -->
<div class="banner-bottom">
    <div class="container">
        <div class="col-md-6 banner_bottom_left">
            <h3>@localizer["Plaka Ceza Sistemi"]</h3><br />
            <p>
                @localizer["Plaka Ceza Sistemi Modülü ile Araçlarınızı ile ilgili bilgilere ulaşıp detayları görüntüleyebilir, Eğer ihlaleriniz mevcut ise ihlal bilgilerini görüntüleyip ilgili birimlere itirazlarda bulunabilirsiniz."]
            </p>
            <div class="wthree_more wthree_more1" style="width: 80%;">
                @if (Authenticated(Context)) { }
                else
                {
                    <a asp-area="" asp-controller="Login" asp-action="Index" class="button--wayra button--border-thick button--text-upper button--size-s">@localizer["ÜYE GİRİŞİ"]</a>
                    <br />
                    <a asp-area="" asp-controller="Signup" asp-action="Index" class="button--wayra button--border-thick button--text-upper button--size-s">@localizer["ÜYE OL"]</a>
                }
            </div>
        </div>

        <div class="col-md-6 banner_bottom_right">
            @if (Authenticated(Context))
            {
                var currentUserId = GetCurrentUserInfo(Context)?.Uid;
                if (currentUserId == null)
                {
                    return;
                }
                var userVehicles = await _vehicleRepository.GetAllFromUserIdAsync(currentUserId);
                var userViolations = await _violationRepository.GetAllFromUserIdAsync(currentUserId);

                <div class="wthree_banner_bottom_right_grids">
                    <div class="col-md-6 banner_bottom_right_grid">
                        <a asp-area="" asp-controller="Vehicle" asp-action="Index">
                            <div class="view view-tenth">
                                <div class="agile_text_box">
                                    <h3>@userVehicles.Count()</h3>
                                    <svg style="height:80px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M135.2 117.4L109.1 192H402.9l-26.1-74.6C372.3 104.6 360.2 96 346.6 96H165.4c-13.6 0-25.7 8.6-30.2 21.4zM39.6 196.8L74.8 96.3C88.3 57.8 124.6 32 165.4 32H346.6c40.8 0 77.1 25.8 90.6 64.3l35.2 100.5c23.2 9.6 39.6 32.5 39.6 59.2V400v48c0 17.7-14.3 32-32 32H448c-17.7 0-32-14.3-32-32V400H96v48c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32V400 256c0-26.7 16.4-49.6 39.6-59.2zM128 288a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zm288 32a32 32 0 1 0 0-64 32 32 0 1 0 0 64z" /></svg>                                    <h3>@localizer["Araçlarım"]</h3>
                                    <p></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6 banner_bottom_right_grid">
                        <a asp-area="" asp-controller="Violation" asp-action="Index">
                            <div class="view view-tenth">
                                <div class="agile_text_box">
                                    <h3>@userViolations.Count()</h3>
                                    <svg style="height:80px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M280 64h40c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128C0 92.7 28.7 64 64 64h40 9.6C121 27.5 153.3 0 192 0s71 27.5 78.4 64H280zM64 112c-8.8 0-16 7.2-16 16V448c0 8.8 7.2 16 16 16H320c8.8 0 16-7.2 16-16V128c0-8.8-7.2-16-16-16H304v24c0 13.3-10.7 24-24 24H192 104c-13.3 0-24-10.7-24-24V112H64zm128-8a24 24 0 1 0 0-48 24 24 0 1 0 0 48z" /></svg>                                    <h3>@localizer["İhlallerim"]</h3>
                                    <p></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            }
            else
            {
                <div class="wthree_banner_bottom_right_grids">
                    <div class="col-md-6 banner_bottom_right_grid">
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            <div class="view view-tenth">
                                <div class="agile_text_box">
                                    <svg style="height:80px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z" /></svg>                                    <h3>@localizer["Ana Sayfa"]</h3>
                                    <p></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6 banner_bottom_right_grid">
                        <a asp-area="" asp-controller="Home" asp-action="Privacy">
                            <div class="view view-tenth">
                                <div class="agile_text_box">
                                    <svg style="height:80px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 0c4.6 0 9.2 1 13.4 2.9L457.7 82.8c22 9.3 38.4 31 38.3 57.2c-.5 99.2-41.3 280.7-213.6 363.2c-16.7 8-36.1 8-52.8 0C57.3 420.7 16.5 239.2 16 140c-.1-26.2 16.3-47.9 38.3-57.2L242.7 2.9C246.8 1 251.4 0 256 0z" /></svg>                                    <h3>@localizer["Gizlilik Sözleşmesi"]</h3>
                                    <p></p>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            }
            <div class="wthree_banner_bottom_right_grids">
                <div class="col-md-6 banner_bottom_right_grid">
                    <a asp-area="" asp-controller="About" asp-action="Index">
                        <div class="view view-tenth">
                            <div class="agile_text_box">
                                <svg style="height:80px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM216 336h24V272H216c-13.3 0-24-10.7-24-24s10.7-24 24-24h48c13.3 0 24 10.7 24 24v88h8c13.3 0 24 10.7 24 24s-10.7 24-24 24H216c-13.3 0-24-10.7-24-24s10.7-24 24-24zm40-208a32 32 0 1 1 0 64 32 32 0 1 1 0-64z" /></svg>                                    <h3>@localizer["Hakkımızda"]</h3>
                                <p></p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-6 banner_bottom_right_grid">
                    <a asp-area="" asp-controller="Contact" asp-action="Index">
                        <div class="view view-tenth">
                            <div class="agile_text_box">
                                <svg style="height:80px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z" /></svg>                                <h3>@localizer["İletişim"]</h3>
                                <p></p>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="clearfix"> </div>
            </div>

        </div>


    </div>
    <div class="clearfix"> </div>
</div>
</div>
<!-- banner-bottom -->
<!-- //about -->
<!-- about-counter -->
<div class="about-counter">
    <div class="container">
        <div class="col-md-3 about_counter_left">
            <i class="fas fa-users" aria-hidden="true"></i>
            <p class="counter">@userCount</p>
            <h3>@localizer["Üye"]</h3>
        </div>
        <div class="col-md-3 about_counter_left">
            <i class="fas fa-car-side" aria-hidden="true"></i>
            <p class="counter">@vehicles.Count()</p>
            <h3>@localizer["Araç"]</h3>
        </div>
        <div class="col-md-3 about_counter_left">
            <i class="fas fa-balance-scale-right" aria-hidden="true"></i>
            <p class="counter">@violations.Count()</p>
            <h3>@localizer["İhlal"]</h3>
        </div>
        <div class="col-md-3 about_counter_left">
            <i class="far fa-file-alt" aria-hidden="true"></i>
            <p class="counter">@contacts.Count()</p>
            <h3>@localizer["İletişim"]</h3>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<!-- //about-counter -->
<!-- about-bottom -->
<div class="about-bottom">
    <div class="container">
        <div class="w3l_about_bottom_grids">
            <div class="col-md-6 w3l_about_bottom_grid_left">
                <h3>@localizer["Plaka Ceza Sistemi"]</h3>
                <p>
                    @localizer["Araç trafiğini izlemede geleneksel yöntemlerle karşılaştırıldığında Plaka Ceza Sistemi yöntemi daha kararlı ve düşük maliyetlidir. Ayrıca mevcut kamera izleme altyapısı üzerinde kurulum yada yeni bir altyapı gerektirmeden plaka tespiti kolaylıkla yapılabilmektedir. Otoyol ve karayollarında belirli sıklıkta bulunan kameralar kullanılarak plaka tespiti yapılabilir. Plakası tespit edilen araçların ceza, vergi borcu, geçmiş muayene zamanı gibi cezalı durumları varsa kolaylıkla tespit edilip gerekli adli, idari işlemlerin yapılmasını kolaylaştıracaktır. Güvenlik güçlerinin iş yükü en aza indirilerek yollardaki güven ve konfor artırılabilecektir."]<br />
                    @localizer["Sistemimiz, Avrupa ve Türkiye başta olmak üzere bir çok ülke de bulunan araçlar için plaka tespiti altyapısını sağlamaktadır. Bu ülkeler de otoyol, karayolu ve bölünmüş yollar gibi yerlerde kurulmuş olan kamera altyapısının yüksekliği ve açısıgibi etmenleriyle uyumludur."]
                </p>
            </div>
            <div class="col-md-6 w3l_about_bottom_grid_right">
                <br />
                <div class='bar_group'>
                    <div class='bar_group__bar thin elastic' label='@localizer["Sistem Kararlılığı Oranı"] : %90' value='262'></div>
                    <div class='bar_group__bar thin elastic' label='@localizer["Plaka Tespİt Algorİtması Doğruluğu"] : %86' value='250'></div>
                    <div class='bar_group__bar thin elastic' label='@localizer["Malİyettekİ Artış Oranı"] : %15' value='44'></div>
                    <div class='bar_group__bar thin elastic' label='@localizer["Sİstem Bakımı Artış Oranı"] : %45' value='130'></div>
                    <div class='bar_group__bar thin elastic' label='@localizer["Yollardakİ GÜven ve Konfordakİ Artış Oranı"] : %35' value='102'></div>
                </div>
                <script src="js/bars.js"></script>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //about-bottom -->